id: P3B409F2E
initial_creation_type: input
source_metadata:
  title: Shechen Gyaltsab Gyurme Pema Namgyal
  language: pt
  description: 'Texts by and about Shechen Gyatsab Gyurme Pema Namgyal (zhe chen rgyal
    tshab ''gyur med padma rnam rgyal, 1871–1926):'
  volume:
    f6e2bff189ca4f729dcc2acd864d2873:
      title: Advice for Gelong Jampa Dargye
      parent: Advice
    49220c2413c34dfa886bbd9cf820ca93:
      title: A Prayer of Aspiration
      parent: Aspiration Prayers
    1ebd63066c9b4ac385e87bc6bee269a1:
      title: Lamp Aspiration Prayer
      parent: Aspiration Prayers
    c8d882d9b724469789d3c031188ee817:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    e4934d04e0214beaa39700611e6b611e:
      title: Brief Offering Prayer to Gesar
      parent: Dharma Protectors
    b1d2c879c8e04212afa63cbdf79dbd00:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Dharma Protectors
    a4f156f97bfd4c829c79973a62f73724:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    f29409c83b314537b0e2f67fd300aa96:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    8d59fab7a832476fb4b888bb55a1cf0a:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    6624eba5619a4571b7dd3bbbceda501e:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    6252f8ea836a450d9f71921ad5057bd2:
      title: A Prayer To Padmasambhava
      parent: Prayers
    25d35bcaeca94411b1e104df1f848e04:
      title: A Prayer to Amitāyus
      parent: Prayers
    346badad9e5c47a9b2ed82579329edaf:
      title: A Prayer to Mañjughoṣa
      parent: Prayers
    fb4783ceef444b8792d752302d05bfa8:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Prayers
    561ab9dc52a7447796d2d881583bf468:
      title: A Concise Feast Prayer
      parent: Tsok
created_at: '2022-03-01T01:34:05.454337'
last_modified_at: '2022-03-01T01:34:05.454367'
